### PR TITLE
Add Additional Scenarios and Updated framework Structure 

### PR DESCRIPTION
**Pull request by poovaraj**
- List of Scenarios : application tab, endpoint tabs
- Updated framework structure

### CODE REVIEW

**Review by markyjackson-taulia — CHANGES_REQUESTED** [review]
Is there an issue for this pr which gives more context for this body of work?

**Comment by poovaraj** [comment]
> Is there an issue for this pr which gives more context for this body of work?

Updated automation framework folder structure and additional scenarios  (features files, step definitions., etc)

**Comment by markyjackson-taulia** [comment]
> > Is there an issue for this pr which gives more context for this body of work?
> 
> 
> 
> Updated automation framework folder structure and additional scenarios  (features files, step definitions., etc) 

Kindly open an issue as well

**Comment by poovaraj** [comment]
> > > Is there an issue for this pr which gives more context for this body of work?
> > 
> > 
> > Updated automation framework folder structure and additional scenarios  (features files, step definitions., etc)
> 
> Kindly open an issue as well

There is no specific issue. It is additional feature added in framework

**Pull request merged**
